# [PROJECT_DIR]/Cargo.toml
[workspace]
resolver = "3" # Rust 2024 edition
members = [
  # Applications
  "rust/apps/open_jsw",
  "rust/apps/jsw_tool",

  # Libraries
  "rust/libs/open_jsw_core",
  "rust/libs/open_jsw_tiled",
  "rust/libs/rust_utils",
]

default-members = [
  # Applications
  "rust/apps/open_jsw",
  "rust/apps/jsw_tool",

  # Libraries
  "rust/libs/open_jsw_core",
  "rust/libs/open_jsw_tiled",
  "rust/libs/rust_utils",
]


[workspace.package]
version = "0.1.0"
authors = ["Richard Sewell"]
description = "A JSW tool"
documentation = "https://TODO.com"
edition = "2024"
rust-version = "1.85.0"

[workspace.dependencies]
open_jsw_core = { path = "rust/libs/open_jsw_core" }
open_jsw_tiled = { path = "rust/libs/open_jsw_tiled" }
rust_utils = { path = "rust/libs/rust_utils" }

# derive_more = { version = "2", features = ["from"] }
thiserror = "2.0"
clap = "4.5"
flexi_logger = "0.29"
log = "0.4"
# byteorder = "1.5"
bytebuffer = "2.3"
macroquad = "0.4"
macroquad-profiler = "0.2"
nanoserde = { version = "0.2.0-beta.0", default-features = false }
image = { version = "0.24", default-features = false }


[workspace.lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.
