# [PROJECT_DIR]/Cargo.toml
[workspace]
resolver = "3" # Rust 2024 edition
members = [
  # Applications
  "apps/open_jsw",
  "apps/jsw_tool",

  # Libraries
  "libs/open_jsw_core",
]

default-members = [
  # Applications
  "apps/open_jsw",
  "apps/jsw_tool",

  # Libraries
  "libs/open_jsw_core",
]


[workspace.package]
version = "0.1.0"
authors = ["Richard Sewell"]
description = "A JSW tool"
documentation = "https://TODO.com"
edition = "2024"
rust-version = "1.85.0"

[workspace.dependencies]
open_jsw_core = { path = "libs/open_jsw_core" }
# derive_more = { version = "2", features = ["from"] }
thiserror = "2"
clap = "4"
flexi_logger = "0"
log = "0"
# byteorder = "1"
bytebuffer = "2"
macroquad = "0"


[workspace.lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.
