[package]
name = "jsw_binary_lib"
version.workspace = true
edition.workspace = true

[dependencies]
bytebuffer = { workspace = true }
# byteorder = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
